// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:amble/shared/models/app_theme_mode.dart';
import 'package:amble/shared/models/behavior_target_type.dart';
import 'package:amble/shared/models/category.dart';
import 'package:amble/shared/models/recurrence_frequency.dart';
import 'package:amble/shared/models/recurrence_rule.dart';
import 'package:amble/shared/models/synced_calendar_event.dart';
import 'package:amble/shared/models/task.dart';
import 'package:amble/shared/models/task_category.dart';
import 'package:amble/shared/models/task_size.dart';
import 'package:amble/shared/models/task_status.dart';
import 'package:amble/shared/models/task_template.dart';
import 'package:amble/shared/models/tracked_behavior.dart';
import 'package:amble/shared/models/zone.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppThemeModeAdapter());
    registerAdapter(BehaviorTargetTypeAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(RecurrenceFrequencyAdapter());
    registerAdapter(RecurrenceRuleAdapter());
    registerAdapter(SyncedCalendarEventAdapter());
    registerAdapter(TaskAdapter());
    registerAdapter(TaskCategoryAdapter());
    registerAdapter(TaskSizeAdapter());
    registerAdapter(TaskStatusAdapter());
    registerAdapter(TaskTemplateAdapter());
    registerAdapter(TrackedBehaviorAdapter());
    registerAdapter(ZoneAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppThemeModeAdapter());
    registerAdapter(BehaviorTargetTypeAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(RecurrenceFrequencyAdapter());
    registerAdapter(RecurrenceRuleAdapter());
    registerAdapter(SyncedCalendarEventAdapter());
    registerAdapter(TaskAdapter());
    registerAdapter(TaskCategoryAdapter());
    registerAdapter(TaskSizeAdapter());
    registerAdapter(TaskStatusAdapter());
    registerAdapter(TaskTemplateAdapter());
    registerAdapter(TrackedBehaviorAdapter());
    registerAdapter(ZoneAdapter());
  }
}
