'use strict';
const $=s=>document.querySelector(s),motion=new RiosMotion($('#stage'));
window.rios=motion;
const fields=[['duration','Duration',5,14,.1,'s'],['amplitude','Bend depth',15,90,1,'px'],['wavelength','Bend length',420,900,10,'px'],['spacing','Lane spacing',14,40,1,'px'],['stroke','Line weight',4,14,.5,'px'],['individuality','Individuality',0,1,.05,''],['dots','Tail opacity',0,1,.05,''],['tailCount','Tail dots',0,6,1,''],['tailSpacing','Tail spacing',10,35,1,'px'],['tailSize','First dot size',2,9,.5,'px'],['tailTaper','Tail taper',0,.9,.05,''],['tailStagger','Dot stagger',0,.18,.01,'s'],['exitStagger','Wave exit stagger',0,.3,.02,'s'],['hold','Logo hold',.5,1.5,.1,'']];
fields.push(['formationStagger','Formation stagger',0,.3,.01,''],['scaleStagger','Scale-down stagger',0,.3,.01,''],['letterStagger','Letter stagger',0,.15,.005,''],['letterFade','Letter fade',.25,1.2,.05,''],['frontDots','Right-side dots',0,1,.05,''],['tailFollowDelay','Tail follow delay',0,1.2,.05,''],['exitWavelength','Exit bend length',160,360,10,'px']);
for(let i=fields.length-1;i>=0;i--)if(['wavelength','exitWavelength'].includes(fields[i][0]))fields.splice(i,1);
fields.push(['entranceFrequency','Entrance waves / screen',1,6,.1,''],['exitFrequency','Exit waves / screen',1,6,.1,''],['exitDepth','Exit bend depth',4,70,1,'px'],['dropRate','Tail emission frequency · 0 = fixed',0,6,.25,'/s'],['morphLead','Formation lead-in · before arrival',0,1.6,.05,''],['formationDuration','Formation duration',.35,1.3,.05,''],['dispersionDuration','Dispersion duration',1.2,4,.1,''],['textRevealLead','Text reveal during settling',0,1.6,.05,''],['textExitOffset','Text exit offset · vs waves',-.6,.6,.05,''],['textExitFade','Text exit fade',.2,1.4,.05,''],['bubbleLinger','Settling bubbles · lifetime',.5,3,.1,''],['bubbleEmission','Bubbles · emission window',.2,3,.1,''],['bubbleRate','Bubbles · emission rate',1,12,1,''],['bubbleStagger','Bubbles · lane stagger',0,.6,.02,''],['bubbleRandomness','Bubbles · randomness',0,1,.05,''],['bubbleTravel','Bubble travel distance',25,220,5,'px'],['bubbleSpread','Bubble dispersion',0,160,5,'px'],['logoGap','Mark to wordmark gap',0,80,1,'px'],['fontWeight','Wordmark font weight',400,900,100,''],['letterSpacing','Wordmark letter spacing',-2,10,.25,'px'],['assembledLogoScale','Logo size · formation and lockup',.6,1.5,.05,'×']);
fields.forEach(([key,label,min,max,step,unit])=>{const el=document.createElement('label');el.className='knob';el.innerHTML=`<div><span>${label}</span><output id="value-${key}"></output></div><input aria-label="${label}" id="${key}" type="range" min="${min}" max="${max}" step="${step}">`;$('#knobs').append(el);el.querySelector('input').oninput=e=>{const value=Number(e.target.value);motion.configure({[key]:value,...(key==='entranceFrequency'&&motion.options.linkWaves?{exitFrequency:value}:{})});sync();};});
const fontControl=document.createElement('label');fontControl.className='select';fontControl.innerHTML='Wordmark font<select id="font-family"><option value="system">System UI</option><option value="arial">Arial</option><option value="helvetica">Helvetica Neue</option><option value="georgia">Georgia</option><option value="trebuchet">Trebuchet MS</option><option value="mono">Courier New</option></select>';$('#knobs').append(fontControl);$('#font-family').onchange=e=>motion.configure({fontFamily:e.target.value});
const linkLabel=document.createElement('label');linkLabel.className='select';linkLabel.innerHTML='Match entrance & exit <input id="link-waves" type="checkbox">';$('#knobs').after(linkLabel);$('#link-waves').onchange=e=>{motion.configure({linkWaves:e.target.checked,...(e.target.checked?{exitFrequency:motion.options.entranceFrequency}:{})});$('#exitFrequency').disabled=e.target.checked;sync();};
motion.options.colors.forEach((color,i)=>{const label=document.createElement('label');label.innerHTML=`<input type="color" aria-label="Lane ${i+1} color" value="${color}"> ${i+1}`;$('#colors').append(label);label.querySelector('input').oninput=e=>{const colors=[...motion.options.colors];colors[i]=e.target.value;motion.configure({colors});};});
function sync(){fields.forEach(([key,label,min,max,step,unit])=>{$('#'+key).value=motion.options[key];$('#value-'+key).textContent=motion.options[key]+unit;});$('#font-family').value=motion.options.fontFamily;$('#link-waves').checked=motion.options.linkWaves;$('#exitFrequency').disabled=motion.options.linkWaves;$('#ending').value=motion.options.ending;$('#theme').value=motion.options.theme;$('#background').value=motion.options.background;$('#ink').value=motion.options.ink;$('#seek').max=motion.options.duration;$('#colors').querySelectorAll('input').forEach((e,i)=>e.value=motion.options.colors[i]);}
motion.onupdate=(t,f)=>{$('#seek').value=t;$('#clock').textContent=t.toFixed(2)+' / '+motion.options.duration.toFixed(2);$('#play').textContent=motion.playing?'Pause':'Play';document.querySelectorAll('.phases span').forEach(e=>e.classList.toggle('active',e.textContent.includes(f.stage)));};
motion.onplaystate=()=>$('#play').textContent='Play';
$('#play').onclick=()=>{motion.playing?motion.pause():motion.play();};$('#replay').onclick=()=>motion.replay();$('#seek').oninput=e=>{motion.pause();motion.seek(Number(e.target.value));};$('#ending').onchange=e=>motion.configure({ending:e.target.value});
const preview=$('#preview'),fullscreenButton=$('#fullscreen');
fullscreenButton.onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await preview.requestFullscreen();}catch{fullscreenButton.title='Full screen is unavailable in this browser.';}};
document.addEventListener('fullscreenchange',()=>{const active=document.fullscreenElement===preview;fullscreenButton.textContent=active?'Exit full screen':'Full screen';fullscreenButton.setAttribute('aria-label',active?'Exit full screen':'Enter full screen');});
document.addEventListener('keydown',e=>{if(e.code!=='Space'||e.repeat||e.ctrlKey||e.metaKey||e.altKey||e.target.closest?.('input,select,textarea,button,[contenteditable="true"],[role="slider"]'))return;e.preventDefault();motion.playing?motion.pause():motion.play();});
$('#theme').onchange=e=>{const theme=e.target.value,palettes={dark:{background:'#191919',ink:'#F3F0EB'},light:{background:'#F3F1EF',ink:'#242321'}};motion.configure({theme,...(palettes[theme]||{})});sync();};
$('#background').oninput=e=>{motion.configure({theme:'custom',background:e.target.value});sync();};$('#ink').oninput=e=>{motion.configure({theme:'custom',ink:e.target.value});sync();};
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#save-config').onclick=()=>download(new Blob([JSON.stringify(motion.options,null,2)],{type:'application/json'}),'rios-motion-config.json');
$('#save-svg').onclick=()=>download(new Blob([motion.svg()],{type:'image/svg+xml'}),'rios-frame.svg');
$('#save-png').onclick=async()=>{const url=URL.createObjectURL(new Blob([motion.svg()],{type:'image/svg+xml'}));const image=new Image();image.onload=()=>{const canvas=document.createElement('canvas');canvas.width=1920;canvas.height=1080;canvas.getContext('2d').drawImage(image,0,0,1920,1080);canvas.toBlob(blob=>{if(blob)download(blob,'rios-frame.png');URL.revokeObjectURL(url);});};image.onerror=()=>{URL.revokeObjectURL(url);alert('PNG export could not complete. Please use SVG frame.');};image.src=url;};
$('#reset').onclick=()=>{motion.pause();motion.configure(RiosMotionTools.defaults);motion.seek(0);sync();};sync();
if(matchMedia('(prefers-reduced-motion: reduce)').matches){motion.configure({ending:'hold'});motion.seek(motion.options.duration);sync();}else motion.play();
